language: python
cache:
- bundler
- pip
python:
- '3.6'
- 3.7-dev
services:
- mongodb
install: pip install -r requirements.txt
sudo: false
script:
- python -m unittest discover ./tests -p '*test*.py'
env:
  global:
  - secure: OMPmZOVkfINO9M+CrfsNvsYFLehPcuXfow+ujzKK64MqAwSnak5LVdqX4E8H+0mGF7EUa8HKz5/K4eHwqe7oFNiWAlDFc+HrvkZk3m57QYRcnFXvJGSnGtWGvAKWZqtb6F7Og/KwTKTRceJsYzLZWR0GxQ/3Yvdc427SBBVP1LjG+Kzp50toJL2R3ZXXJuKEKeID9gAx2RTo/sb89fQ1OWJ5qTE/xXkyvF6QX8FhIECrrArNYGmsu8lxbbCvf4RCapyV4/67alqPaB2AvGJgiaNr7R7x1vVuitSvtS5oScVPuG16t/L+nIGmRzqEnBaiKujcP8Mj9XZwbpWFeFh/CtD72pCea6ZW69hqQlq0VhKCvgmCo9ZPTHrTqcWHQf/RlSzBWxze2n2Sk5v/QG+FMqfNcHq18hPkVyHrAYQgvo2uw/pcwXOaDKkHFdKDduutkxI1oZ9JU/cBSCZ/t1fHG1Nvc4gOxCdQraQt3+8NcXkUj09kWF5Vw+JqYQJyWcO7yM9Qm+cBAgArVQHfkL7thOgN0o+PGL5xKaJGbRhs3OY3rdxl5QcV5Ng/EgB7lOHUrGMti9m4tAt2AntF+saHwi3vEH63/mV5JgDxjG9Go4/mrt/UgiY+Rk7T7RYpT0gIaORlCSfcBdI/hA1DU2h3Q4mZiTPmkHeCo07x5Qqg7dI=
  - secure: ElWgzBxRStkLtOeYdhPJ1D0t1K6po0wvhjj1k2FIfyk2+E6phGDdJ5u2qaOGdEgC/ae6plrb/hZQsv16Wr9WXGsuJNvh6tADIiY64msbRIyYUTaWLGyX1HoMa77J0HDXk2LASQPJ93jPYQMn2GHgj8AUdlCznlD1RaDs9yrF0o4Lg46nCPH1ytLuFNgR7o9lPQ2h0aH1bjqOm6ZeRHc+waRwjhMdkhE4pVFF18auxsrT/a/RrVvg3nBjdd4LUSBhl/BOlb2r+cpCze5WqQ5pzXLIpjDdG4oZfJdoayzh98+4oMxH0vhepFYiIUQseUXYUtZ3qPadJKRDESLwuy4atCrvnF3Cw/9Fkxig8QbyWxPtkKpmKRBJUL+BM2b6odKpCLi377JRqwbBj4iHIHLe7SrwjT0e2XsaIclZucHjICHXDbfDJbjRK/k/WO+DXdLOUjTvuSDV5WjHByAObCBlKPqc34I7VDgzclRA3Bo56Uy7tggoLidkhHxa0cJEV15xN7BUJZUhAz9M1yE7V6gHE6PRi/I4LkNW/8Wr2VYFkYRdvLPwTnIL2FphYs/pz5QTxulm1sbVxFDBbkdapcvCr6maucidiDEtD63Uc/wUcEwaYKkZDDhdtQm//rWogwtsARs8V5iCREsyUcrHhT7Rvn7dg4qcGyA7FKLuuG8h9T8=
